//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win11Tunned.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win11Tunned.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminName {
            get {
                return ResourceManager.GetString("AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shellex\ContextMenuHandlers\Compatibility
        ///执行文件 - 兼容性疑难解答
        ///出了问题不去谷歌，看这解答有个卵用。
        ///exefile
        ///
        ///shellex\ContextMenuHandlers\Library Location
        ///文件夹 - 包含到库中
        ///我不用这个系统自带的各种库文件夹，如果要用请勿删除。
        ///Folder
        ///
        ///shellex\ContextMenuHandlers\{90AA3A4E-1CBA-4233-B8BB-535773D48449}
        ///所有文件 - 固定到任务栏
        ///直接往任务栏上拖即可
        ///*
        ///
        ///shell\AnyCode
        ///文件夹及其背景 - Open with Visual Studio
        ///没啥用纯看着碍眼。
        ///Directory
        ///Directory\background
        ///
        ///shell\edit
        ///各种纯文本类文件 - 编辑
        ///跟&quot;记事本打开&quot;的功能重复了，删之。
        ///cmdfile
        ///batfile
        ///xmlfile
        ///regfile
        ///SystemFileAssociations\text
        ///
        ///Shell\setdesktopwallpaper
        ///各种媒体文件 - 设为桌面背景
        ///一般在 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContextMenuRules {
            get {
                return ResourceManager.GetString("ContextMenuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
        ///NoDriveTypeAutoRun
        ///255
        ///关闭自动播放
        ///纯属垃圾功能还有安全风险，不是残疾人都该禁掉。
        ///
        ///HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat
        ///DisablePCA
        ///1
        ///关闭程序兼容性助手
        ///屁用没有的玩意，兼容性怎样还用你来分析？
        ///
        ///HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat
        ///DisableEngine
        ///1
        ///关闭应用程序兼容性引擎
        ///为提升兼容性，微软给一些曾经流行的老软件做了适配，在每次启动应用时都会检查，关闭后提升性能，但老软件可能无法运行。
        ///
        ///HKLM\SOFTWARE\Policies\Microsoft\Windows Defender
        ///DisableAntiSpyware
        ///1
        ///关闭 Windows Defender
        ///我自己是不用杀毒软件的，如果要用还是别关。
        ///
        ///# 这个是用户配置里的，注意不要带 GUID 部分，因为底层 API 会处理。
        ///HKCU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupPolicyRules {
            get {
                return ResourceManager.GetString("GroupPolicyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不播放 Windows 启动声音
        ///看个人喜好，我是比较喜欢安静一点的
        ///DisableStartupSound
        ///
        ///禁止系统失败后写入调试信息
        ///不做系统相关开发的话这些调试信息鸟用没有，如果禁用了虚拟内存还会在事件日志里报错。
        ///DisableCrashDump
        ///
        ///关闭 PerfDiag 事件日志
        ///解决事件查看器中的会话“PerfDiag Logger”未能启动，存在以下错误: 0xC0000035 问题。
        ///DisablePerfDiagLogger
        ///.
        /// </summary>
        internal static string RegistryRules {
            get {
                return ResourceManager.GetString("RegistryRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 发传真的那个关闭系统功能后会自动删除。
        ///
        ///Compressed (zipped) Folder.ZFSendToTarget
        ///有专门压缩软件来做了。
        ///
        ///文档.mydocs
        ///就是个直接复制到用户的文档目录，可惜我不用它。
        ///.
        /// </summary>
        internal static string SendToRules {
            get {
                return ResourceManager.GetString("SendToRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 多个服务依赖它，等实现了依赖检测后再说
        ///#BFE
        ///#Windows 安全平台的核心服务，防火墙和杀毒软件都需要，如果不用它们倒是可以关了
        ///#Disabled
        ///
        ///DPS
        ///屁用没有的诊断功能，出了问题不 Google 谁看这玩意
        ///Disabled
        ///
        ///DiagTrack
        ///给诊断服务提供数据的，如果不用诊断功能可以关了，据某些用户说会占用较多资源
        ///Disabled
        ///
        ///hidserv
        ///如果你没有 HID 设备就可以禁用，该服务还容易被攻击者利用
        ///Disabled
        ///
        ///ShellHWDetection
        ///这年头谁还玩自动播放，该服务也容易被攻击者利用，建议禁了
        ///Disabled
        ///
        ///WSearch
        ///系统自带的搜索功能，挺占磁盘的，如果不需要高级搜索功能就关了吧
        ///Disabled
        ///
        ///PcaSvc
        ///啥卵用都没有的兼容性助手
        ///Disabled
        ///
        ///IKEEXT
        ///某些协议的 VPN 需要这个服务，不用的话可以关掉
        ///Disabled
        ///
        ///# 默认手动
        ///SecurityHealthService
        ///如果你关闭了安全中心监视的某项，他会不停地提示你，很烦人建议关了
        ///Disabled
        ///
        ///TrkWks
        ///个人用户很少会把 NTFS 文件链接到远程计 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceRules {
            get {
                return ResourceManager.GetString("ServiceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft\Windows\Application Experience
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///
        ///Microsoft\Windows\Autochk
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///
        ///Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///
        ///Microsoft\Windows\Customer Experience Improvement Program
        ///全是客户体验改善计划，不参加的直接删光光
        ///
        ///Microsoft\Windows\Application Experience\StartupAppTask
        ///启动项应该自己注意，而不是靠它来扫描
        ///:DISABLE
        ///
        ///Microsoft\Windows\DiskCleanup\SilentCleanup
        ///什么傻逼任务，磁盘空间不足还用你来提示？？？
        ///:DISABLE
        ///
        ///Microsoft\Windows\Windows Error Reporting\QueueRepor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TaskSchdulerRules {
            get {
                return ResourceManager.GetString("TaskSchdulerRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用自动播放
        ///这年头谁还用这功能，而且自动行为容易有安全问题。
        ///DisableAutoPlay
        ///
        ///优化资源管理器选项
        ///显示文件扩展名、自动扩展到当前目录、不显示库等，优化后需要在资源管理器里刷新一下。
        ///ExplorerOptions
        ///
        ///优化任务栏设置
        ///不合并按钮，显示所有托盘图标等，总之不要隐藏信息，除非你会同时开十几个程序否则任务栏是用不满的。
        ///Taskbar
        ///
        ///禁用辅助功能
        ///就是禁用筛选键、粘滞键、鼠标键、切换键等等东西，如果不是残疾人就没用，一不小心就按出来相当烦人。
        ///DisableAccessibility
        ///
        ///增强网络安全性
        ///具体操作包括：禁用友好错误信息，禁用代理自动检测设置。
        ///IESecurity
        ///
        ///简化视觉效果
        ///除了“显示缩略图而不是显示图标”和“拖动时显示窗口内容”外全部关闭，避免各种效果浪费时间和性能。
        ///VisualEffects
        ///.
        /// </summary>
        internal static string UserRegistryRules {
            get {
                return ResourceManager.GetString("UserRegistryRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some optimizations require administrator privileges.
        /// </summary>
        internal static string UserTooltip {
            get {
                return ResourceManager.GetString("UserTooltip", resourceCulture);
            }
        }
    }
}
