//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win11Tunned.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win11Tunned.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\_Test_Import\Key]
        ///&quot;StringValue&quot;=&quot;中文内容&quot;
        ///
        ///.
        /// </summary>
        internal static string ImportTest {
            get {
                return ResourceManager.GetString("ImportTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\_Test_Kinds]
        ///&quot;Test&quot;=foobar:00000123
        ///
        ///.
        /// </summary>
        internal static string InvalidKind {
            get {
                return ResourceManager.GetString("InvalidKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; 每种类型的值都有一个
        ///
        ///[HKEY_CURRENT_USER\_Test_Kinds]
        ///@=&quot;文字文字&quot;
        ///&quot;Binary&quot;=hex:fa,51,6f,89
        ///&quot;Dword&quot;=dword:00000123
        ///&quot;Qword&quot;=hex(b):88,68,66,00,00,00,00,00
        ///&quot;Multi&quot;=hex(7):53,00,74,00,72,00,30,00,00,00,53,00,74,00,72,00,31,00,00,00,00,\
        ///  00
        ///&quot;Expand&quot;=hex(2):25,00,55,00,53,00,45,00,52,00,50,00,52,00,4f,00,46,00,49,00,4c,\
        ///  00,45,00,25,00,00,00
        ///
        ///.
        /// </summary>
        internal static string Kinds {
            get {
                return ResourceManager.GetString("Kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///&quot;StringValue&quot;=&quot;中文内容&quot;
        ///
        ///.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\测试项]
        ///
        ///[HKEY_CLASSES_ROOT\测试项\bar]
        ///
        ///[HKEY_CLASSES_ROOT\测试项\bar\key]
        ///
        ///[HKEY_CLASSES_ROOT\测试项\baz]
        ///
        ///[HKEY_CLASSES_ROOT\测试项\foo]
        ///
        ///[HKEY_CLASSES_ROOT\测试项\foo\key]
        ///
        ///.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\_Test_Kinds]
        ///&quot;Multi&quot;=hex(7):53,00,74,00,\
        ///  72,00,30,00,00\
        ///  
        ///.
        /// </summary>
        internal static string TruncatedValue {
            get {
                return ResourceManager.GetString("TruncatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\_Test_Kinds]
        ///&quot;Multi&quot;=hex(7):53,00,74,00,\ ;测试多行 + 注释
        ///  72,00,30,00,\
        ///  ;注释在值内占一行
        ///  00,00,53,00,74,00,72,00,31,00,00,00,00,\
        ///  00
        ///
        ///.
        /// </summary>
        internal static string ValueParts {
            get {
                return ResourceManager.GetString("ValueParts", resourceCulture);
            }
        }
    }
}
