//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win11Tuned.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win11Tuned.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminName {
            get {
                return ResourceManager.GetString("AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 没有移除“用 Windows Defender 扫描”，因为禁用 Windows Defender 之后该项自然会移除。
        ///
        ///shellex\ContextMenuHandlers\Compatibility
        ///执行文件 - 兼容性疑难解答
        ///出了问题不去谷歌，看这解答有个卵用。
        ///exefile
        ///
        ///shellex\ContextMenuHandlers\Library Location
        ///文件夹 - 包含到库中
        ///我不用这个系统自带的各种库文件夹，如果要用请勿删除。
        ///Folder
        ///
        ///# 属性页 PropertySheetHandlers 里也有，但不是右键菜单就不管它。
        ///shellex\ContextMenuHandlers\{596AB062-B4D2-4215-9F74-E9109B0A8153}
        ///还原以前的版本
        ///不用文件版本功能的可以移除，不影响属性页。
        ///AllFilesystemObjects
        ///CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}
        ///Directory
        ///Drive
        ///WOW6432Node\CLSID\{450D8FBA-AD25-11D0-98A8-0800 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContextMenuRules {
            get {
                return ResourceManager.GetString("ContextMenuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Icons.
        /// </summary>
        internal static string DesktopIcons {
            get {
                return ResourceManager.GetString("DesktopIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Policy.
        /// </summary>
        internal static string GroupPolicy {
            get {
                return ResourceManager.GetString("GroupPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
        ///NoDriveTypeAutoRun
        ///255
        ///关闭自动播放
        ///纯属垃圾功能还有安全风险，不是残疾人都该禁掉。
        ///
        ///HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection
        ///AllowTelemetry
        ///0
        ///禁止发送诊断数据
        ///不向 Microsoft 发送诊断数据，该策略的说明上写着教育版和企业版才能禁止。
        ///
        ///HKLM\SOFTWARE\Policies\Microsoft\Windows\System
        ///UploadUserActivities
        ///0
        ///禁止上传用户活动数据
        ///禁止把浏览历史、搜索记录、什么时候打开了 UWP 应用这些东西上传到 Microsoft。
        ///
        ///HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization
        ///NoLockScreen
        ///1
        ///关闭锁屏界面
        ///即使关了也可以锁定用户，此时显示登录界面，我不知道这个锁屏有什么用。
        ///
        ///HKCU\Software\Policies\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupPolicyRules {
            get {
                return ResourceManager.GetString("GroupPolicyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts File.
        /// </summary>
        internal static string HostsFile {
            get {
                return ResourceManager.GetString("HostsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string OtherRules {
            get {
                return ResourceManager.GetString("OtherRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁止 TrustedInstaller 生成垃圾
        ///在修改 Windows 功能、更新系统时，TrustedInstaller 会记录日志并备份 WinSxS 中的旧组件，占用大量空间，你用不着它们就禁了。
        ///AvoidCBSGarbage
        ///HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing
        ///
        ///不播放 Windows 启动声音
        ///看个人喜好，我是比较喜欢安静一点的
        ///DisableStartupSound
        ///
        ///不下载恶意软件删除工具
        ///Windows 更新会夹带一个屁用没有的恶意软件删除工具，不需要的话可以禁止下载它。
        ///DontOfferMRT
        ///
        ///禁止系统失败后写入调试信息
        ///不做系统相关开发的话这些调试信息鸟用没有，如果禁用了虚拟内存还会在事件日志里报错。
        ///DisableCrashDump
        ///
        ///禁止程序崩溃后创建转储文件
        ///Windows 默认在程序崩溃后会自动创建一个转储文件到 %LOCALAPPDATA%\CrashDumps 目录，你不调试它的话就没用，可以关闭该功能。
        ///DisableLocalDu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RegistryRules {
            get {
                return ResourceManager.GetString("RegistryRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu Clean.
        /// </summary>
        internal static string RemoveContextMenu {
            get {
                return ResourceManager.GetString("RemoveContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendTo Clean.
        /// </summary>
        internal static string SendToClean {
            get {
                return ResourceManager.GetString("SendToClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 发传真的那个关闭系统功能后会自动删除。
        ///
        ///Compressed (zipped) Folder.ZFSendToTarget
        ///有专门压缩软件来做了。
        ///
        ///文档.mydocs
        ///就是个直接复制到用户的文档目录，可惜我不用它。
        ///.
        /// </summary>
        internal static string SendToRules {
            get {
                return ResourceManager.GetString("SendToRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # WinHttpAutoProxySvc 禁用后【网络和 Internet/代理】显示异常
        ///# TabletInputService 禁用墨迹服务会导致输入法无法启动，表现为无限访问 OOBE\LaunchUserOOBE 键。
        ///# SensorService 禁用后控制面板的 Power &amp; Battery 会崩溃。
        ///# DisplayEnhancementService 禁用后无法调节屏幕亮度。
        ///# SecurityHealthService 整合到 Microsoft Defender 规则里了。
        ///
        ///BDESVC
        ///不使用 BitLocker 加密的话可以禁了，禁用后 设置/BitLocker 不可用，默认手动但必定会被启动。
        ///Disabled
        ///
        ///DPS
        ///屁用没有的诊断功能，出了问题不 Google 谁看这玩意
        ///Disabled
        ///
        ///DiagTrack
        ///收集用户信息的，如果不想分享给微软就可以关了，据某些用户说会占用较多资源
        ///Disabled
        ///
        ///DusmSvc
        ///统计以及限制网络流量的服务，如果没使用计费的网络就可以关掉，注意关闭后 Network &amp; internet 控制面板上面的 大图标、Proper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceRules {
            get {
                return ResourceManager.GetString("ServiceRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Clean.
        /// </summary>
        internal static string StartupClean {
            get {
                return ResourceManager.GetString("StartupClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (System).
        /// </summary>
        internal static string SystemScope {
            get {
                return ResourceManager.GetString("SystemScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string SystenSettings {
            get {
                return ResourceManager.GetString("SystenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft\Windows\Application Experience
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///DELETE:DIRECTORY
        ///
        ///Microsoft\Windows\Autochk
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///DELETE:DIRECTORY
        ///
        ///Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector
        ///客户体验改善计划相关的任务，没同意的可以删了
        ///DELETE
        ///
        ///Microsoft\Windows\Customer Experience Improvement Program
        ///全是客户体验改善计划，不参加的直接删光光
        ///DELETE:DIRECTORY
        ///
        ///Microsoft\Windows\Feedback\Siuf
        ///Windows 反馈的任务，会收集用户信息，建议删了
        ///DELETE:DIRECTORY
        ///
        ///Microsoft\Windows\DiskCleanup\SilentCleanup
        ///什么傻逼任务，磁盘空间不足还用你来提示？？？
        ///
        ///Microsoft\W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TaskSchdulerRules {
            get {
                return ResourceManager.GetString("TaskSchdulerRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler Clean.
        /// </summary>
        internal static string TaskScheduler {
            get {
                return ResourceManager.GetString("TaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Preinstalled Apps.
        /// </summary>
        internal static string UninstallApps {
            get {
                return ResourceManager.GetString("UninstallApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.BingSearch
        ///Microsoft.BingNews
        ///Microsoft.BingWeather
        ///Microsoft.GamingApp
        ///Microsoft.GetHelp
        ///Microsoft.Getstarted
        ///Microsoft.Messaging
        ///Microsoft.Microsoft3DViewer
        ///Microsoft.MicrosoftOfficeHub
        ///Microsoft.MicrosoftStickyNotes
        ///Microsoft.MicrosoftSolitaireCollection
        ///Microsoft.NetworkSpeedTest
        ///Microsoft.Office
        ///Microsoft.OneConnect
        ///Microsoft.OutlookForWindows
        ///Microsoft.People
        ///Microsoft.Print3D
        ///Microsoft.ScreenSketch
        ///Microsoft.SkypeApp
        ///Microsoft.Todos
        ///Microsoft.WindowsAlarms
        ///Microsoft.WindowsFeedbackHub
        ///Micro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UninstallAppxRules {
            get {
                return ResourceManager.GetString("UninstallAppxRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示任务栏右侧的通知铃铛
        ///如果通知出现的时候人不在，可能就会错过，显示这个铃铛可以通过颜色判断有无未读消息，建议开启。
        ///ShowNotificationBell
        ///
        ///禁用自动播放
        ///这年头谁还用这功能，而且自动行为容易有安全问题。
        ///DisableAutoPlay
        ///
        ///禁用系统截屏快捷键
        ///如果安装了第三方截屏工具，且使用 PrintScreen 作为快捷键则需要关闭系统的。
        ///DisableSinppingKey
        ///
        ///优化资源管理器选项
        ///显示文件扩展名、自动扩展到当前目录、不显示库等，优化后需要在资源管理器里刷新一下。
        ///ExplorerOptions
        ///
        ///不显示最近使用的文件
        ///禁止资源管理器在快速访问栏里自动记录最近使用的文件。
        ///ExplorerPrivacy
        ///
        ///优化任务栏设置
        ///不合并按钮，显示所有托盘图标等，总之不要隐藏信息，除非你会同时开十几个程序否则任务栏是用不满的。
        ///Taskbar
        ///
        ///恢复经典右键菜单
        ///Win11 的新菜单设计的像个傻逼，赶紧退回去！
        ///ClassicContextMenu
        ///
        ///命令行默认使用 CMD
        ///Windows11 默认使用新版 Windows Terminal 运行命令，这会导致一些兼容问题比如 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserRegistryRules {
            get {
                return ResourceManager.GetString("UserRegistryRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (User).
        /// </summary>
        internal static string UserScope {
            get {
                return ResourceManager.GetString("UserScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some optimizations require administrator privileges.
        /// </summary>
        internal static string UserTooltip {
            get {
                return ResourceManager.GetString("UserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UWP Apps.
        /// </summary>
        internal static string UWPApps {
            get {
                return ResourceManager.GetString("UWPApps", resourceCulture);
            }
        }
    }
}
